# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: battleship.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x62\x61ttleship.proto\"\x94\x03\n\nbattleship\x12)\n\talignment\x18\x01 \x01(\x0e\x32\x16.battleship.alignments\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0e\n\x06length\x18\x03 \x01(\x02\x12,\n\nship_class\x18\x04 \x01(\x0e\x32\x18.battleship.ship_classes\x12\x11\n\tcrew_size\x18\x05 \x01(\x05\x12\r\n\x05\x61rmed\x18\x06 \x01(\x08\x12%\n\x08officers\x18\x07 \x03(\x0b\x32\x13.battleship.officer\x1a>\n\x07officer\x12\x12\n\nfirst_name\x18\x01 \x01(\t\x12\x11\n\tlast_name\x18\x02 \x01(\t\x12\x0c\n\x04rank\x18\x03 \x01(\t\"!\n\nalignments\x12\x08\n\x04\x41lly\x10\x00\x12\t\n\x05\x45nemy\x10\x01\"c\n\x0cship_classes\x12\x0c\n\x08\x43orvette\x10\x00\x12\x0b\n\x07\x46rigate\x10\x01\x12\x0b\n\x07\x43ruiser\x10\x02\x12\r\n\tDestroyer\x10\x03\x12\x0b\n\x07\x43\x61rrier\x10\x04\x12\x0f\n\x0b\x44readnought\x10\x05\"*\n\x13\x63oordinates_request\x12\x13\n\x0b\x63oordinates\x18\x01 \x01(\x02\x32H\n\x0c\x45xploreSpace\x12\x38\n\x0fget_battleships\x12\x14.coordinates_request\x1a\x0b.battleship\"\x00\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'battleship_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BATTLESHIP']._serialized_start=21
  _globals['_BATTLESHIP']._serialized_end=425
  _globals['_BATTLESHIP_OFFICER']._serialized_start=227
  _globals['_BATTLESHIP_OFFICER']._serialized_end=289
  _globals['_BATTLESHIP_ALIGNMENTS']._serialized_start=291
  _globals['_BATTLESHIP_ALIGNMENTS']._serialized_end=324
  _globals['_BATTLESHIP_SHIP_CLASSES']._serialized_start=326
  _globals['_BATTLESHIP_SHIP_CLASSES']._serialized_end=425
  _globals['_COORDINATES_REQUEST']._serialized_start=427
  _globals['_COORDINATES_REQUEST']._serialized_end=469
  _globals['_EXPLORESPACE']._serialized_start=471
  _globals['_EXPLORESPACE']._serialized_end=543
# @@protoc_insertion_point(module_scope)
