"""Create speed column

Revision ID: a7d7a6832adc
Revises: 3b3ccf43314b
Create Date: 2024-07-24 12:47:45.805249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7d7a6832adc'
down_revision: Union[str, None] = '3b3ccf43314b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_ship', sa.Column('speed', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('data_ship', 'speed')
    # ### end Alembic commands ###
