"""Create tables

Revision ID: 3b3ccf43314b
Revises: ae954849f892
Create Date: 2024-07-24 12:46:18.948715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b3ccf43314b'
down_revision: Union[str, None] = 'ae954849f892'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_officer',
    sa.Column('officer_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('rank', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('officer_id'),
    sa.UniqueConstraint('first_name', 'last_name', 'rank')
    )
    op.create_table('data_ship',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('alignment', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('class', sa.String(), nullable=False),
    sa.Column('length', sa.Float(), nullable=False),
    sa.Column('crew_size', sa.Integer(), nullable=False),
    sa.Column('armed', sa.Boolean(), nullable=False),
    sa.Column('officer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['officer_id'], ['data_officer.officer_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'officer_id')
    )
    op.create_table('data_traitor',
    sa.Column('traitor_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('officer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['officer_id'], ['data_officer.officer_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('traitor_id'),
    sa.UniqueConstraint('officer_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('data_traitor')
    op.drop_table('data_ship')
    op.drop_table('data_officer')
    # ### end Alembic commands ###
